<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>RobloxImageFix-Setup</AssemblyName>
    <Version>1.2.0</Version>
  </PropertyGroup>

  <ItemGroup Condition="Exists('AppBundle.zip')">
    <EmbeddedResource Include="AppBundle.zip" LogicalName="AppBundle.zip" />
  </ItemGroup>

</Project>
